version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: AWSSDK.SQS
    versions:
    - 3.5.1.12
    - 3.5.1.13
    - 3.5.1.14
    - 3.5.1.15
    - 3.5.1.16
    - 3.5.1.17
    - 3.5.1.18
    - 3.5.1.19
    - 3.5.1.20
    - 3.5.1.21
    - 3.5.1.22
    - 3.5.1.24
    - 3.5.1.25
    - 3.5.1.26
    - 3.5.1.27
    - 3.7.0
    - 3.7.0.10
    - 3.7.0.11
    - 3.7.0.12
    - 3.7.0.13
    - 3.7.0.14
    - 3.7.0.15
    - 3.7.0.2
    - 3.7.0.3
    - 3.7.0.4
    - 3.7.0.7
    - 3.7.0.8
    - 3.7.0.9
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
  - dependency-name: System.Text.Json
    versions:
    - 5.0.1
  - dependency-name: Azure.Storage.Queues
    versions:
    - 12.6.0
